WIP: qeglfscontext.cpp: drop last EGLenum param
New 5.3.1 doesn't support
/OE/qt5-qpa-hwcomposer-plugin/5.2.0+gitrAUTOINC+ee9a40af8f-r0/git/hwcomposer/qeglfscontext.cpp: In constructor 'QEglFSCon
text::QEglFSContext(HwComposerContext*, QEglFSPageFlipper*, const QSurfaceFormat&, QPlatformOpenGLContext*, EGLDisplay, EGLenum)':
/OE/qt5-qpa-hwcomposer-plugin/5.2.0+gitrAUTOINC+ee9a40af8f-r0/git/hwcomposer/qeglfscontext.cpp:55:75: error: no matching function for call to 'QEGLPlatformContext::QEGLPlatformContext(QSurfaceFormat, QPlatformOpenGLContext*&, void*&, EGLConfig, EGLenum&)'
     m_hwc(hwc), m_pageFlipper(pageFlipper), m_swapIntervalConfigured(false)
                                                                           ^
/OE/qt5-qpa-hwcomposer-plugin/5.2.0+gitrAUTOINC+ee9a40af8f-r0/git/hwcomposer/qeglfscontext.cpp:55:75: note: candidates are:
In file included from /OE/qt5-qpa-hwcomposer-plugin/5.2.0+gitrAUTOINC+ee9a40af8f-r0/git/hwcomposer/qeglfscontext.h:46:0,
                 from /OE/qt5-qpa-hwcomposer-plugin/5.2.0+gitrAUTOINC+ee9a40af8f-r0/git/hwcomposer/qeglfscontext.cpp:42:
/OE/tenderloin/usr/include/qt5/QtPlatformSupport/5.3.1/QtPlatformSupport/private/qeglplatformcontext_p.h:55:5: note: QEGLPlatformContext::QEGLPlatformContext(const QSurfaceFormat&, QPlatformOpenGLContext*, EGLDisplay, EGLConfig)
     QEGLPlatformContext(const QSurfaceFormat &format, QPlatformOpenGLContext *share, EGLDisplay display,
     ^
/OE/tenderloin/usr/include/qt5/QtPlatformSupport/5.3.1/QtPlatformSupport/private/qeglplatformcontext_p.h:55:5: note:   candidate expects 4 arguments, 5 provided
/OE/tenderloin/usr/include/qt5/QtPlatformSupport/5.3.1/QtPlatformSupport/private/qeglplatformcontext_p.h:54:5: note: QEGLPlatformContext::QEGLPlatformContext(const QSurfaceFormat&, QPlatformOpenGLContext*, EGLDisplay)
     QEGLPlatformContext(const QSurfaceFormat &format, QPlatformOpenGLContext *share, EGLDisplay display);
     ^
/OE/tenderloin/usr/include/qt5/QtPlatformSupport/5.3.1/QtPlatformSupport/private/qeglplatformcontext_p.h:54:5: note:   candidate expects 3 arguments, 5 provided
/OE/qt5-qpa-hwcomposer-plugin/5.2.0+gitrAUTOINC+ee9a40af8f-r0/git/hwcomposer/qeglfscontext.cpp: In member function 'virtual bool QEglFSContext::makeCurrent(QPlatformSurface*)':
/OE/qt5-qpa-hwcomposer-plugin/5.2.0+gitrAUTOINC+ee9a40af8f-r0/git/hwcomposer/qeglfscontext.cpp:75:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
Makefile:528: recipe for target '.obj/qeglfscontext.o' failed
make: *** [.obj/qeglfscontext.o] Error 1
ERROR: oe_runmake failed
O

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>